# File : .pep8speaks.yml

scanner:
    diff_only: True
    linter: pycodestyle  # Other option is flake8

pycodestyle:  # Same as scanner.linter value.
    max-line-length: 79  # Default in PEP 8
    ignore:  # Errors and warnings to ignore
        - W503  # line break before binary operator
        - E203

