name: packaging

on:
  # Make sure packaging process is not broken
  push:
    branches:
      - master
      - dev
      - 'release/**'
  pull_request:
  # Make a package for release
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools setuptools_scm twine wheel build
    - name: Create packages
      run: python -m build .
    - name: Run twine check
      run: twine check dist/*
    - uses: actions/upload-artifact@v4
      with:
        name: tox-gh-actions-dist
        path: dist
